SELECT DISTINCT BASE_DT, AGREE_ID, FLAG, ACCT_NO, ACCT_BR, REGION, AREA, BRANCH, GCIF_NO, CIF_NO,
SUB_PROD_NM, SEGMENT, GCIF_NAME, PROD_TYPE, CURR_CODE, RATE_DPK, BASE_AMOUNT, NPK_SALES, COLT
FROM PDA.MASTER_FUNDING
WHERE 
((agree_id LIKE 'ST%' AND STATUS NOT IN ('03','04','05') AND system_type LIKE '8%' AND ctrl3 <>'797')
OR (agree_id like 'IM%' and status not in ('04','05','08') and system_type like '8%' and ctrl3 <>'797' ))
AND NOT SEGMENT = 'CFS-RB-5MB' 
AND BASE_DT=(SELECT MAX(BASE_DT) FROM PDA.MASTER_FUNDING)
--AND BASE_DT= '20241008'